
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulation extends Simulation {

	val httpProtocol = http
		.baseURL("https://api.noon.com")
		.inferHtmlResources()
		.contentTypeHeader("application/json")
		.doNotTrackHeader(""""1"""")
		.userAgentHeader("Apache-HttpClient/4.5.2 (Java/1.8.0_111)")

	val headers_0 = Map(
		"" -> "authority: api.noon.com",
		"accept" -> "application/json",
		"accept-encoding" -> "gzip, deflate, br",
		"authorization" -> "Bearer ${token}")

	val headers_29 = Map(
		"" -> "authority: api.noon.com",
		"accept" -> "application/json",
		"accept-encoding" -> "gzip, deflate, br",
		"authorization" -> "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXMiOnsidWlkIjoiREY0MkQ0QTQtQTQxQS00MEU1LUJGMjAtNkJDNEEzNEY5OUFFIiwidHJjIjoxLCJ0eWsiOiIiLCJyc2siOiIifSwic3ViIjoiYyIsIndhbGxldCI6eyJkb21haW4iOiJOT09OIn0sImlzcyI6Im5vb24uY29tIiwiZXhwIjoxNDg0MjE0NTYxLCJpYXQiOjE0ODQxMjgxNjEsInVzZXJJZCI6ImRmNDJkNGE0LWE0MWEtNDBlNS1iZjIwLTZiYzRhMzRmOTlhZSIsImp0aSI6IiIsInJleHAiOjE0ODQyMTQ1NjF9.J5Jf2eMMrNmmMsq2KFmPKp7EhcAF02O7rSKSTDeLDeo")

	val headers_58 = Map(
		"" -> "authority: api.noon.com",
		"accept" -> "application/json",
		"accept-encoding" -> "gzip, deflate, br",
		"authorization" -> "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXMiOnsidWlkIjoiREY0MkQ0QTQtQTQxQS00MEU1LUJGMjAtNkJDNEEzNEY5OUFFIiwidHJjIjoxLCJ0eWsiOiIiLCJyc2siOiIifSwic3ViIjoiYyIsIndhbGxldCI6eyJkb21haW4iOiJOT09OIn0sImlzcyI6Im5vb24uY29tIiwiZXhwIjoxNDg0MjE0NTYyLCJpYXQiOjE0ODQxMjgxNjIsInVzZXJJZCI6ImRmNDJkNGE0LWE0MWEtNDBlNS1iZjIwLTZiYzRhMzRmOTlhZSIsImp0aSI6IiIsInJleHAiOjE0ODQyMTQ1NjJ9.40Js4HdPKbWcqwV641oB7439udpMxxSXektBRJpi7hQ")

	val headers_105 = Map(
		"" -> "authority: api.noon.com",
		"accept" -> "application/json",
		"accept-encoding" -> "gzip, deflate, br",
		"authorization" -> "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXMiOnsidWlkIjoiREY0MkQ0QTQtQTQxQS00MEU1LUJGMjAtNkJDNEEzNEY5OUFFIiwidHJjIjoxLCJ0eWsiOiIiLCJyc2siOiIifSwic3ViIjoiYyIsIndhbGxldCI6eyJkb21haW4iOiJOT09OIn0sImlzcyI6Im5vb24uY29tIiwiZXhwIjoxNDg0MjE0NTY1LCJpYXQiOjE0ODQxMjgxNjUsInVzZXJJZCI6ImRmNDJkNGE0LWE0MWEtNDBlNS1iZjIwLTZiYzRhMzRmOTlhZSIsImp0aSI6IiIsInJleHAiOjE0ODQyMTQ1NjV9.OtRrrxtGQ17ldr9ZWMqV2oHzlISyMsMfFS9p5tKmDAA")

    val uri1 = "https://api.noon.com:443"

	val scn = scenario("RecordedSimulation")
		.exec(http("request_0")
			.get("/customer-experience/recommendation")
			.headers(headers_0)
			.resources(http("request_1")
			.get("/customer-experience/version")
			.headers(headers_0),
            http("request_2")
			.get("/pricing-engine/version")
			.headers(headers_0),
            http("request_3")
			.get("/cp-offer-management/version")
			.headers(headers_0),
            http("request_4")
			.get("/wallet/version")
			.headers(headers_0),
            http("request_5")
			.get("/customer-review/version")
			.headers(headers_0),
            http("request_6")
			.get("/customer-experience/reviews/1238934922_10000000000199_0/brief")
			.headers(headers_0),
            http("request_7")
			.get("/customer-experience/search/suggested_searches?query=Pixel")
			.headers(headers_0),
            http("request_8")
			.get("/microservice-auth/health")
			.headers(headers_0),
            http("request_9")
			.get("/wishlist/version")
			.headers(headers_0)
			.check(status.is(502)),
            http("request_10")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0010_request.txt")),
            http("request_11")
			.get("/consumer-profile/version")
			.headers(headers_0),
            http("request_12")
			.get("/bank-gateway/health")
			.headers(headers_0)
			.check(status.is(502)),
            http("request_13")
			.get("/customer-experience/pages/home")
			.headers(headers_0),
            http("request_14")
			.get("/user-management/health")
			.headers(headers_0),
            http("request_15")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0015_request.txt")),
            http("request_16")
			.get("/cp-category/health")
			.headers(headers_0),
            http("request_17")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0017_request.txt")),
            http("request_18")
			.get("/cp-returns/version")
			.headers(headers_0),
            http("request_19")
			.get("/customer-experience/products/10000000000199")
			.headers(headers_0),
            http("request_20")
			.get("/customer-experience/products/10000000000199")
			.headers(headers_0),
            http("request_21")
			.get("/cp-ordermanagement/version")
			.headers(headers_0),
            http("request_22")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0022_request.txt")),
            http("request_23")
			.get("/wallet/health")
			.headers(headers_0),
            http("request_24")
			.get("/customer-experience/search/suggested_searches?query=%D8%B3")
			.headers(headers_0),
            http("request_25")
			.get("/customer-experience/reviews/1238934922_10000000000199_0/all")
			.headers(headers_0),
            http("request_26")
			.get("/pricing-engine/health")
			.headers(headers_0),
            http("request_27")
			.get("/consumer-profile/health")
			.headers(headers_0),
            http("request_28")
			.get("/customer-experience/pages/category/fashion")
			.headers(headers_0),
            http("request_29")
			.get("/seller/sellers")
			.headers(headers_29),
            http("request_30")
			.get("/cp-offer-management/health")
			.headers(headers_0),
            http("request_31")
			.get("/customer-experience/health")
			.headers(headers_0),
            http("request_32")
			.get("/customer-review/health")
			.headers(headers_0),
            http("request_33")
			.get("/cp-returns/health")
			.headers(headers_0),
            http("request_34")
			.get("/customer-experience/products/1238934922_10000000000199_0/offers")
			.headers(headers_0),
            http("request_35")
			.get("/customer-experience/products/1238934922_10000000000199_0/offers")
			.headers(headers_0),
            http("request_36")
			.get("/user-management/version")
			.headers(headers_0),
            http("request_37")
			.get("/customer-experience/wallet/payment_instruments")
			.headers(headers_29),
            http("request_38")
			.get("/cp-category/version")
			.headers(headers_0),
            http("request_39")
			.get("/seller/sellers/341703254")
			.headers(headers_29)
			.check(status.is(404)),
            http("request_40")
			.get("/customer-experience/pages/category/home-office")
			.headers(headers_0),
            http("request_41")
			.get("/microservice-auth/version")
			.headers(headers_0),
            http("request_42")
			.get("/customer-review/reviews/1238934922_10000000000199_0")
			.headers(headers_0),
            http("request_43")
			.get("/cp-ordermanagement/health")
			.headers(headers_0),
            http("request_44")
			.get("/customer-experience/returns/returnable_items")
			.headers(headers_29),
            http("request_45")
			.get("/seller/sellers")
			.headers(headers_29),
            http("request_46")
			.get("/customer-experience/products/10000000000199/image%20")
			.headers(headers_0)
			.check(status.is(403)),
            http("request_47")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0047_request.txt")),
            http("request_48")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0048_request.txt")),
            http("request_49")
			.get("/seller/sellers/1dd6c8a6-b026-4cea-9157-2fecd81abf3d")
			.headers(headers_29),
            http("request_50")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0050_request.txt")),
            http("request_51")
			.get("/customer-experience/pages/category/sports-recreation")
			.headers(headers_0),
            http("request_52")
			.get("/cp-category/random-categories/2")
			.headers(headers_0),
            http("request_53")
			.get("/customer-experience/wallet/instruments")
			.headers(headers_29),
            http("request_54")
			.get("/bank-gateway/version")
			.headers(headers_0)
			.check(status.is(502)),
            http("request_55")
			.get("/customer-review/reviews/brief")
			.headers(headers_0),
            http("request_56")
			.get("/customer-experience/sellers/341703254/offers")
			.headers(headers_29)
			.check(status.is(404)),
            http("request_57")
			.get("/customer-experience/products/10000000000199/image/main%20")
			.headers(headers_0)
			.check(status.is(403)),
            http("request_58")
			.get("/wallet/wallet")
			.headers(headers_58),
            http("request_59")
			.get("/consumer-profile/consumers")
			.headers(headers_58),
            http("request_60")
			.get("/customer-experience/search")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0060_request.txt")),
            http("request_61")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0061_request.txt")),
            http("request_62")
			.get("/cp-category/subcategories")
			.headers(headers_0),
            http("request_63")
			.get("/seller/sellers/1dd6c8a6-b026-4cea-9157-2fecd81abf3d/bank-details")
			.headers(headers_29),
            http("request_64")
			.get("/customer-experience/pages/category/health-beauty-family")
			.headers(headers_0),
            http("request_65")
			.get("/customer-experience/account/one_click_setting")
			.headers(headers_58)
			.check(status.is(500)),
            http("request_66")
			.get("/customer-experience/sellers/341703254/offers/search?query=simplymahmoud@gmail.com")
			.headers(headers_29)
			.check(status.is(404)),
            http("request_67")
			.get("/seller/sellers/341703254/offers")
			.headers(headers_29)
			.check(status.is(404)),
            http("request_68")
			.get("/cp-category/subcategories/toys")
			.headers(headers_0),
            http("request_69")
			.get("/wallet/wallet/transactions")
			.headers(headers_58),
            http("request_70")
			.get("/consumer-profile/consumers/df42d4a4-a41a-40e5-bf20-6bc4a34f99ae/public_info")
			.headers(headers_58),
            http("request_71")
			.get("/cp-ordermanagement/consumers/df42d4a4-a41a-40e5-bf20-6bc4a34f99ae/orders")
			.headers(headers_58),
            http("request_72")
			.post("/user-management/user/account")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0072_request.txt")),
            http("request_73")
			.get("/customer-experience/pages/category/entertainment-leisure")
			.headers(headers_0),
            http("request_74")
			.get("/customer-experience/account/myorders")
			.headers(headers_58),
            http("request_75")
			.get("/customer-experience/sellers/341703254/order/search?query=simplymahmoud@gmail.com")
			.headers(headers_29)
			.check(status.is(404)),
            http("request_76")
			.get("/cp-category/subcategories/baby")
			.headers(headers_0),
            http("request_77")
			.get("/consumer-profile/account/addresses")
			.headers(headers_58),
            http("request_78")
			.get("/customer-experience/search")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0078_request.txt")),
            http("request_79")
			.get("/cp-ordermanagement/consumers/df42d4a4-a41a-40e5-bf20-6bc4a34f99ae/returnableItems")
			.headers(headers_58),
            http("request_80")
			.get("/wallet/wallet/transactions-with-instruments")
			.headers(headers_58),
            http("request_81")
			.get("/customer-experience/pages/category/electronics-appliances")
			.headers(headers_0),
            http("request_82")
			.post("/consumer-profile/account/addresses/default")
			.headers(headers_58)
			.body(RawFileBody("RecordedSimulation_0082_request.txt")),
            http("request_83")
			.get("/cp-category/subcategories/health")
			.headers(headers_0),
            http("request_84")
			.get("/customer-experience/pages/category/uncategorized-products")
			.headers(headers_0),
            http("request_85")
			.post("/user-management/user/account")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0085_request.txt")),
            http("request_86")
			.get("/cp-category/subcategories/beauty")
			.headers(headers_0),
            http("request_87")
			.post("/consumer-profile/account/addresses/deliverable")
			.headers(headers_58)
			.body(RawFileBody("RecordedSimulation_0087_request.txt")),
            http("request_88")
			.get("/customer-experience/pages/category/fashion/items")
			.headers(headers_0),
            http("request_89")
			.get("/cp-category/subcategories/sports")
			.headers(headers_0),
            http("request_90")
			.put("/consumer-profile/account/language_preference")
			.headers(headers_58)
			.body(RawFileBody("RecordedSimulation_0090_request.txt")),
            http("request_91")
			.get("/cp-category/subcategories/fashion")
			.headers(headers_0),
            http("request_92")
			.get("/customer-experience/pages/category/home-office/items")
			.headers(headers_0),
            http("request_93")
			.get("/cp-category/subcategories/exclusive")
			.headers(headers_0),
            http("request_94")
			.get("/customer-experience/pages/category/sports-recreation/items")
			.headers(headers_0),
            http("request_95")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0095_request.txt"))
			.check(status.is(401)),
            http("request_96")
			.get("/cp-category/subcategories/electronics")
			.headers(headers_0),
            http("request_97")
			.post("/user-management/user/renew")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0097_request.txt"))
			.check(status.is(500)),
            http("request_98")
			.get("/customer-experience/pages/category/health-beauty-family/items")
			.headers(headers_0),
            http("request_99")
			.get("/cp-category/subcategories/home-office")
			.headers(headers_0),
            http("request_100")
			.get("/cp-category/subcategories/todays-deals")
			.headers(headers_0),
            http("request_101")
			.get("/customer-experience/pages/category/entertainment-leisure/items")
			.headers(headers_0),
            http("request_102")
			.post("/user-management/user/login")
			.headers(headers_0)
			.body(RawFileBody("RecordedSimulation_0102_request.txt")),
            http("request_103")
			.get("/cp-category/subcategories/entertainment")
			.headers(headers_0),
            http("request_104")
			.get("/customer-experience/pages/category/electronics-appliances/items")
			.headers(headers_0),
            http("request_105")
			.post("/user-management/user/renew")
			.headers(headers_105)
			.body(RawFileBody("RecordedSimulation_0105_request.txt")),
            http("request_106")
			.get("/cp-category/subcategories/featured-brands")
			.headers(headers_0),
            http("request_107")
			.get("/customer-experience/pages/category/uncategorized-products/items")
			.headers(headers_0),
            http("request_108")
			.post("/user-management/user/logout")
			.headers(headers_105)
			.body(RawFileBody("RecordedSimulation_0108_request.txt")),
            http("request_109")
			.get("/cp-category/subcategories/sports-recreation")
			.headers(headers_0),
            http("request_110")
			.get("/cp-category/subcategories/health-beauty-family")
			.headers(headers_0),
            http("request_111")
			.get("/cp-category/subcategories/entertainment-leisure")
			.headers(headers_0),
            http("request_112")
			.get("/cp-category/subcategories/electronics-appliances")
			.headers(headers_0),
            http("request_113")
			.get("/customer-experience/pages/category/fashion/items_all")
			.headers(headers_0),
            http("request_114")
			.get("/cp-category/subcategories/pacifiers-teething-rings")
			.headers(headers_0),
            http("request_115")
			.get("/cp-category/subcategories/uncategorized-products")
			.headers(headers_0),
            http("request_116")
			.get("/cp-category/subcategories/air-fresheners-deoderizers")
			.headers(headers_0),
            http("request_117")
			.get("/customer-experience/pages/category/home-office/items_all")
			.headers(headers_0),
            http("request_118")
			.get("/customer-experience/pages/category/sports-recreation/items_all")
			.headers(headers_0),
            http("request_119")
			.get("/cp-category/subcategories/toys/leaf")
			.headers(headers_0),
            http("request_120")
			.get("/cp-category/subcategories/baby/leaf")
			.headers(headers_0),
            http("request_121")
			.get("/customer-experience/pages/category/health-beauty-family/items_all")
			.headers(headers_0),
            http("request_122")
			.get("/cp-category/subcategories/health/leaf")
			.headers(headers_0),
            http("request_123")
			.get("/cp-category/subcategories/beauty/leaf")
			.headers(headers_0),
            http("request_124")
			.get("/customer-experience/pages/category/entertainment-leisure/items_all")
			.headers(headers_0),
            http("request_125")
			.get("/cp-category/subcategories/sports/leaf")
			.headers(headers_0),
            http("request_126")
			.get("/customer-experience/pages/category/electronics-appliances/items_all")
			.headers(headers_0),
            http("request_127")
			.get("/cp-category/subcategories/fashion/leaf")
			.headers(headers_0),
            http("request_128")
			.get("/cp-category/subcategories/exclusive/leaf")
			.headers(headers_0),
            http("request_129")
			.get("/customer-experience/pages/category/uncategorized-products/items_all")
			.headers(headers_0),
            http("request_130")
			.get("/cp-category/subcategories/electronics/leaf")
			.headers(headers_0),
            http("request_131")
			.get("/cp-category/subcategories/home-office/leaf")
			.headers(headers_0),
            http("request_132")
			.get("/cp-category/subcategories/todays-deals/leaf")
			.headers(headers_0),
            http("request_133")
			.get("/cp-category/subcategories/entertainment/leaf")
			.headers(headers_0),
            http("request_134")
			.get("/cp-category/subcategories/featured-brands/leaf")
			.headers(headers_0),
            http("request_135")
			.get("/cp-category/subcategories/sports-recreation/leaf")
			.headers(headers_0),
            http("request_136")
			.get("/cp-category/subcategories/health-beauty-family/leaf")
			.headers(headers_0),
            http("request_137")
			.get("/cp-category/subcategories/entertainment-leisure/leaf")
			.headers(headers_0),
            http("request_138")
			.get("/cp-category/subcategories/electronics-appliances/leaf")
			.headers(headers_0),
            http("request_139")
			.get("/cp-category/subcategories/pacifiers-teething-rings/leaf")
			.headers(headers_0),
            http("request_140")
			.get("/cp-category/subcategories/uncategorized-products/leaf")
			.headers(headers_0),
            http("request_141")
			.get("/cp-category/subcategories/air-fresheners-deoderizers/leaf")
			.headers(headers_0),
            http("request_142")
			.get("/cp-category/subcategories/toys/all")
			.headers(headers_0),
            http("request_143")
			.get("/cp-category/subcategories/baby/all")
			.headers(headers_0),
            http("request_144")
			.get("/cp-category/subcategories/health/all")
			.headers(headers_0),
            http("request_145")
			.get("/cp-category/subcategories/beauty/all")
			.headers(headers_0),
            http("request_146")
			.get("/cp-category/subcategories/sports/all")
			.headers(headers_0),
            http("request_147")
			.get("/cp-category/subcategories/fashion/all")
			.headers(headers_0),
            http("request_148")
			.get("/cp-category/subcategories/exclusive/all")
			.headers(headers_0),
            http("request_149")
			.get("/cp-category/subcategories/electronics/all")
			.headers(headers_0),
            http("request_150")
			.get("/cp-category/subcategories/home-office/all")
			.headers(headers_0),
            http("request_151")
			.get("/cp-category/subcategories/todays-deals/all")
			.headers(headers_0),
            http("request_152")
			.get("/cp-category/subcategories/entertainment/all")
			.headers(headers_0),
            http("request_153")
			.get("/cp-category/subcategories/featured-brands/all")
			.headers(headers_0),
            http("request_154")
			.get("/cp-category/subcategories/sports-recreation/all")
			.headers(headers_0),
            http("request_155")
			.get("/cp-category/subcategories/health-beauty-family/all")
			.headers(headers_0),
            http("request_156")
			.get("/cp-category/subcategories/entertainment-leisure/all")
			.headers(headers_0),
            http("request_157")
			.get("/cp-category/subcategories/electronics-appliances/all")
			.headers(headers_0),
            http("request_158")
			.get("/cp-category/subcategories/pacifiers-teething-rings/all")
			.headers(headers_0),
            http("request_159")
			.get("/cp-category/subcategories/uncategorized-products/all")
			.headers(headers_0),
            http("request_160")
			.get("/cp-category/subcategories/air-fresheners-deoderizers/all")
			.headers(headers_0),
            http("request_161")
			.get("/cp-category/category-hierarchy/toys")
			.headers(headers_0),
            http("request_162")
			.get("/cp-category/category-hierarchy/baby")
			.headers(headers_0),
            http("request_163")
			.get("/cp-category/category-hierarchy/health")
			.headers(headers_0),
            http("request_164")
			.get("/cp-category/category-hierarchy/beauty")
			.headers(headers_0),
            http("request_165")
			.get("/cp-category/category-hierarchy/sports")
			.headers(headers_0),
            http("request_166")
			.get("/cp-category/category-hierarchy/fashion")
			.headers(headers_0),
            http("request_167")
			.get("/cp-category/category-hierarchy/exclusive")
			.headers(headers_0),
            http("request_168")
			.get("/cp-category/category-hierarchy/electronics")
			.headers(headers_0),
            http("request_169")
			.get("/cp-category/category-hierarchy/home-office")
			.headers(headers_0),
            http("request_170")
			.get("/cp-category/category-hierarchy/todays-deals")
			.headers(headers_0),
            http("request_171")
			.get("/cp-category/category-hierarchy/entertainment")
			.headers(headers_0),
            http("request_172")
			.get("/cp-category/category-hierarchy/featured-brands")
			.headers(headers_0),
            http("request_173")
			.get("/cp-category/category-hierarchy/sports-recreation")
			.headers(headers_0),
            http("request_174")
			.get("/cp-category/category-hierarchy/health-beauty-family")
			.headers(headers_0),
            http("request_175")
			.get("/cp-category/category-hierarchy/entertainment-leisure")
			.headers(headers_0),
            http("request_176")
			.get("/cp-category/category-hierarchy/electronics-appliances")
			.headers(headers_0),
            http("request_177")
			.get("/cp-category/category-hierarchy/pacifiers-teething-rings")
			.headers(headers_0),
            http("request_178")
			.get("/cp-category/category-hierarchy/air-fresheners-deoderizers")
			.headers(headers_0),
            http("request_179")
			.get("/cp-category/categories/fashion")
			.headers(headers_0),
            http("request_180")
			.get("/cp-category/categories/home-office")
			.headers(headers_0),
            http("request_181")
			.get("/cp-category/categories/sports-recreation")
			.headers(headers_0),
            http("request_182")
			.get("/cp-category/categories/health-beauty-family")
			.headers(headers_0),
            http("request_183")
			.get("/cp-category/categories/entertainment-leisure")
			.headers(headers_0),
            http("request_184")
			.get("/cp-category/categories/electronics-appliances")
			.headers(headers_0),
            http("request_185")
			.get("/cp-category/categories/pacifiers-teething-rings")
			.headers(headers_0),
            http("request_186")
			.get("/cp-category/categories/uncategorized-products")
			.headers(headers_0),
            http("request_187")
			.get("/cp-category/categories/air-fresheners-deoderizers")
			.headers(headers_0),
            http("request_188")
			.get("/cp-category/banners/toys")
			.headers(headers_0),
            http("request_189")
			.get("/cp-category/banners/baby")
			.headers(headers_0),
            http("request_190")
			.get("/cp-category/banners/health")
			.headers(headers_0),
            http("request_191")
			.get("/cp-category/banners/beauty")
			.headers(headers_0),
            http("request_192")
			.get("/cp-category/banners/sports")
			.headers(headers_0),
            http("request_193")
			.get("/cp-category/banners/fashion")
			.headers(headers_0),
            http("request_194")
			.get("/cp-category/banners/exclusive")
			.headers(headers_0),
            http("request_195")
			.get("/cp-category/banners/electronics")
			.headers(headers_0),
            http("request_196")
			.get("/cp-category/banners/home-office")
			.headers(headers_0),
            http("request_197")
			.get("/cp-category/banners/todays-deals")
			.headers(headers_0),
            http("request_198")
			.get("/cp-category/banners/entertainment")
			.headers(headers_0),
            http("request_199")
			.get("/cp-category/banners/featured-brands")
			.headers(headers_0),
            http("request_200")
			.get("/cp-category/banners/sports-recreation")
			.headers(headers_0),
            http("request_201")
			.get("/cp-category/banners/health-beauty-family")
			.headers(headers_0),
            http("request_202")
			.get("/cp-category/banners/entertainment-leisure")
			.headers(headers_0),
            http("request_203")
			.get("/cp-category/banners/electronics-appliances")
			.headers(headers_0),
            http("request_204")
			.get("/cp-category/banners/pacifiers-teething-rings")
			.headers(headers_0),
            http("request_205")
			.get("/cp-category/banners/uncategorized-products")
			.headers(headers_0),
            http("request_206")
			.get("/cp-category/banners/air-fresheners-deoderizers")
			.headers(headers_0))
			.check(status.is(404)))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}